#!/usr/bin/env bash
# Installs Nginx and configures it on the remote server

apt-get -y update
apt-get -y install nginx
ufw allow 'Ngiinx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
