#!/usr/bin/env bash
# Installs Nginx and configures it on the remote server

err_loc="root /var/www/html/;\n\t\tinternal;"
err="error_page 404 /404.html;\n\tlocation /404.html {\n\t\t$err_loc"

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER:$USER" /var/www/
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i "0,/}/ s|}|}\n\n\t$err|" /etc/nginx/sites-available/default
sudo service nginx restart
