#!/usr/bin/env bash
# Installs Nginx and configures it on the remote server

err_loc="root /var/www/html/;\n\t\tinternal;\n\t}"
err="error_page 404 /404.html;\n\tlocation /404.html {\n\t\t$err_loc"
link="https://www.youtube.com/watch?v=EJC-_j3SnXk"
pattern=":80 default_server;"
header="\n\tadd_header X-Served-By \$HOSTNAME;"


sudo apt -y update
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER:$USER" /var/www/
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo sed -i "/server_name _;/a \ \trewrite ^/redirect_me/$ $link permanent;" /etc/nginx/sites-available/default

sudo sed -i "0,/}/ s|}|}\n\n\t$err|" /etc/nginx/sites-available/default

sudo sed -i "0,/$pattern/ s|$pattern|$pattern$header|" /etc/nginx/sites-available/default

sudo service nginx restart
