#!/usr/bin/env bash
# making a story out of the content of the file /etc/passwd

while IFS=':' read -r user pw uid gid u_info home shell
do
	echo "The user $user is part of the $gid gang,"\
	"lives in $home and rides $shell. $uid's place is protected"\
	"by the passcode $pw, more info about the user here: $u_info"
done < "/etc/passwd"
